### ISSUE TITLE
Cannot run run_test in run_tests.py

### ISSUE THREAD

**Issue by hadidayekh** [Leslieaj/InferDynamic#1]
Hello,
I am trying to run the function `run_test` you provide in the `run_tests.py` file to explore your code and comparisons between dbscan, tolmerge, and piecelinear methods, however, I am stumbling upon an error in the SVM classification problem.
I uncommented the lines 478, 483, and 488 of the file `run_tests.py` to preserve the signature you provide to use `run_test`.

The error I'm getting is the following:
```
Traceback (most recent call last):
  File "/Users/dk/Documents/git-repos/InferDynamic/run_tests.py", line 478, in <module>
    run_test(i+1, 'A', i, methods=['dbscan','tolmerge', 'piecelinear'])
  File "/Users//Documents/git-repos/InferDynamic/run_tests.py", line 116, in run_test
    P, G, boundary = infer_model(
  File "/Users/dk/Documents/git-repos/InferDynamic/infer_multi_ch.py", line 2426, in infer_model
    coeffs = svm_classify(P, Y, L_y, boundary_order, num_mode)
  File "/Users/dk/Documents/git-repos/InferDynamic/infer_multi_ch.py", line 1719, in svm_classify
    return get_coeffs(m, order=boundary_order)
  File "/Users/dk/Documents/git-repos/InferDynamic/infer_multi_ch.py", line 1683, in get_coeffs
    list_a[d] += svc[i][0] * 0.5 * sv[i][d+1]
KeyError: 3
```

I am running on macOS Montery 12.5.1 with Python 3.9.10. I have all the dependency libraries you mention installed.

**Comment by Jinxy0979** [comment]
Thank you for providing this issue, it seems like a problem of svm. We use libsvm with version 3.23. We run our code just now with no such error and successfully reproduce the result. We comment 480,482,485,487,490 and uncomment 478, in other words, we test model A. The results are as followed:
```bash
PS C:\Users\jinxy\git\InferDynamic> & C:/Anaconda3/python.exe c:/Users/jinxy/git/InferDynamic/run_tests.py       
1 & $A$ & 2 & 0.100 & 50 & 0.010 & 0.00096 & 0.00047 & 0.00047& & 0.2 & 0.7 & 0.5& & \\
2 & $A$ & 3 & 0.100 & 50 & 0.010 & 0.00080 & 0.00001 & 0.00001& & 0.3 & 1.2 & 0.8& & \\
3 & $A$ & 2 & 0.200 & 50 & 0.010 & 0.00100 & 0.00001 & 0.00096& & 0.1 & 0.3 & 0.4& & \\
4 & $A$ & 3 & 0.200 & 50 & 0.010 & 0.00001 & 0.00001 & 0.00002& & 0.1 & 0.7 & 0.5& & \\
```

**Comment by hadidayekh** [comment]
Thank you. I did not have the correct libsvm installed.
